sudo: required

language: node_js

node_js:
  - "8.0.0"

services:
  - docker

stages:
  - build
  - tag

env:
  - IMAGE="$DOCKER_REGISTRY/elixir/dsw-client" IMAGE_TAG="$IMAGE:$TRAVIS_COMMIT" IMAGE_TAG_LATEST="$IMAGE:latest" IMAGE_TAG_VERSION="$IMAGE:$TRAVIS_TAG"

install:
  - npm install


before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - npm test
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

    - stage: tag
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: false
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_LATEST
        - docker push $IMAGE_TAG_LATEST

    - stage: tag
      if: tag =~ ^v
      install: false
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_VERSION
        - docker push $IMAGE_TAG_VERSION
